"""initial

Revision ID: f697305bb47d
Revises: 
Create Date: 2026-06-04 15:16:31.910182
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'f697305bb47d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('ability_name', sa.String(length=64), nullable=False),
    sa.Column('ability_text', sa.Text(), nullable=False),
    sa.Column('play_style', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('color_primary', sa.String(length=7), nullable=False),
    sa.Column('color_secondary', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('ink', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('faction_code', sa.String(length=16), nullable=False),
    sa.Column('card_type', sa.String(length=16), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('grit', sa.Integer(), nullable=True),
    sa.Column('spirit', sa.Integer(), nullable=True),
    sa.Column('effect_text', sa.Text(), nullable=False),
    sa.Column('effect_code', sa.String(length=64), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('flavor_text', sa.Text(), nullable=False),
    sa.Column('artist', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_token', sa.Boolean(), nullable=False),
    sa.Column('set_code', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['faction_code'], ['factions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('faction_code', sa.String(length=16), nullable=False),
    sa.Column('ally_faction_code', sa.String(length=16), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faction_code'], ['factions.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('p1_id', sa.Uuid(), nullable=False),
    sa.Column('p2_id', sa.Uuid(), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=True),
    sa.Column('p1_deck_id', sa.Uuid(), nullable=False),
    sa.Column('p2_deck_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('turns_played', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['p1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['p2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'card_id')
    )
    op.create_table('user_cards',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cards')
    op.drop_table('deck_cards')
    op.drop_table('matches')
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('factions')
    # ### end Alembic commands ###
